Repository FUNZIP-Dev/FUNZIP, pull requests merged in 2023-06, with the labels that each got.

#5 Feat#4 order/step
  src/@components/common/tutorial/style.tsx
  src/@components/common/tutorial/tutorial.tsx
  src/@components/order/orderFooter/orderFooter.tsx
  src/@components/order/orderFooter/style.tsx
  src/@components/order/orderHeader/orderHeader.tsx
  src/@components/order/orderHeader/style.tsx
  src/@components/order/orderMain/orderMain.tsx
  src/@components/order/orderMain/style.tsx
  src/@pages/order/order.tsx
  src/assets/icon/orderStep1Ic.svg
  src/assets/icon/orderStep2Ic.svg
  src/assets/icon/orderStep3Ic.svg
  src/assets/icon/orderStep4Ic.svg
  src/assets/icon/orderStepBlankIc.svg
  src/assets/icon/tutorialMainIc.svg
  src/assets/index.ts
  src/core/order/orderStep.ts
  src/recoil/order/stepRender.ts
  src/style/theme.ts
  src/type/order/stepProps.ts
Labels: feat-function, feat-UI, 지수

#7 Feat#6 order/tutorial
  src/@components/common/tutorial/style.tsx
  src/@components/common/tutorial/tutorial.tsx
  src/@components/order/orderBuy/orderBuy.tsx
  src/@components/order/orderBuy/style.tsx
  src/@components/order/orderCategory/orderCategory.tsx
  src/@components/order/orderCategory/style.tsx
  src/@components/order/orderMain/orderMain.tsx
  src/@components/order/orderOption/orderOption.tsx
  src/@components/order/orderOption/style.tsx
  src/@components/order/orderStyle/orderStyle.tsx
  src/@components/order/orderStyle/style.tsx
  src/@components/order/orderTutorial/orderTutorial.tsx
  src/@components/order/orderTutorial/style.tsx
  src/@pages/order/order.tsx
  src/assets/icon/orderTutorialXIc.svg
  src/assets/index.ts
  src/style/theme.ts
  src/type/order/stepProps.ts
Labels: feat-function, feat-UI, 지수

#11 :sparkles: Feat : 푸터 구현
  src/@components/order/orderFooter/orderFooter.tsx
  src/@components/order/orderFooter/style.tsx
  src/assets/icon/orderNextBtnIc.svg
  src/assets/icon/orderPreviousBtnIc.svg
  src/assets/icon/orderSuccessBtnIc.svg
  src/assets/index.ts
  src/style/theme.ts
Labels: feat-function, feat-UI, 지수

#13 Feat#12 order/option
  src/@components/order/orderFooter/style.tsx
  src/@components/order/orderOption/orderOption.tsx
  src/@components/order/orderOption/style.tsx
  src/assets/icon/orderOptionCheckActiveIc.svg
  src/assets/icon/orderOptionCheckIc.svg
  src/assets/index.ts
  src/core/order/optionList.tsx
  src/recoil/order/selectOptions.ts
  src/style/theme.ts
Labels: feat-function, feat-UI, 지수

#16 Feat#1 setting/firebase
  .gitignore
  package-lock.json
  package.json
  src/@components/common/nav/nav.tsx
  src/@pages/Auth/login.tsx
  src/@pages/Auth/style.tsx
  src/@pages/review/review.tsx
  src/@pages/review/style.tsx
  src/Router.tsx
  src/context/authContext.tsx
  src/fbase.tsx
  src/main.tsx
  src/provider/authProvider.tsx
  yarn.lock
Labels: enhancement, feat-function, 희찬

#20 Feat#1 profile
  src/@components/Auth/loginForm.tsx
  src/@components/Auth/loginTitle.tsx
  src/@components/Auth/signUpForm.tsx
  src/@components/Auth/signUpGoogleForm.tsx
  src/@components/Auth/style.tsx
  src/@components/common/loading.tsx
  src/@components/common/nav/nav.tsx
  src/@pages/Auth/login.tsx
  src/@pages/Auth/style.tsx
  src/@pages/myPage/myPage.tsx
  src/App.tsx
  src/Router.tsx
  src/assets/icon/googleIcon.svg
  src/assets/icon/loginLogo.svg
  src/assets/icon/mypageLogo.svg
  src/assets/icon/profileDefaultIcon.svg
  src/assets/index.ts
  src/assets/spinner.gif
Labels: 희찬

#22 Feat#1 profile : 마이페이지 프로세스
  src/@components/Auth/signUpForm.tsx
  src/@components/Auth/style.tsx
  src/@components/myPage/mainLogo.tsx
  src/@components/myPage/style.tsx
  src/@pages/Auth/login.tsx
  src/@pages/Auth/style.tsx
  src/@pages/myPage/myPage.tsx
  src/@pages/myPage/style.tsx
  src/assets/icon/MainBackground/main1.svg
  src/assets/icon/MainBackground/main10.svg
  src/assets/icon/MainBackground/main2.svg
  src/assets/icon/MainBackground/main3.svg
  src/assets/icon/MainBackground/main4.svg
  src/assets/icon/MainBackground/main5.svg
  src/assets/icon/MainBackground/main6.svg
  src/assets/icon/MainBackground/main7.svg
  src/assets/icon/MainBackground/main8.svg
  src/assets/icon/MainBackground/main9.svg
  src/assets/icon/mypageLogo.svg
  src/assets/index.ts
Labels: feat-function, feat-UI, 희찬

#27 Feat#25 faq/UI
  src/@pages/faq/faq.tsx
  src/@pages/faq/style.ts
  src/assets/icon/faqRepresentativeIc.svg
  src/assets/icon/faqToggleIc.svg
  src/assets/icon/faqToggleOpenIc.svg
  src/assets/index.ts
  src/core/faq/faqData.ts
Labels: feat-function, feat-UI, 지수

#34 Feat#29 faq/get api
  src/@pages/faq/faq.tsx
  src/@pages/faq/style.ts
  src/@pages/review/review.tsx
  src/api/.keep
  src/api/getFaqData.ts
  src/core/faq/faqData.ts
  src/fbase.tsx
  src/provider/authProvider.tsx
Labels: feat-function, feat-UI, 지수

#35 Feat#28 order/post api
  src/@components/common/nav/nav.tsx
  src/@components/order/orderBuy/orderBuy.tsx
  src/@components/order/orderBuy/style.ts
  src/@components/order/orderCategory/orderCategory.tsx
  src/@components/order/orderFooter/orderFooter.tsx
  src/@components/order/orderOption/orderOption.tsx
  src/@components/order/orderStyle/orderStyle.tsx
  src/@components/order/orderStyle/preview/preview.tsx
  src/@components/order/orderStyle/preview/style.ts
  src/@components/order/orderStyle/step1/step1.tsx
  src/@components/order/orderStyle/step4/step4.tsx
  src/@components/order/orderStyle/step4/style.ts
  src/@components/order/orderStyle/step5/step5.tsx
  src/@components/order/orderStyle/step5/style.ts
  src/@components/order/orderTutorial/orderTutorial.tsx
  src/@pages/Auth/login.tsx
  src/@pages/faq/faq.tsx
  src/@pages/faq/style.ts
  src/@pages/main/main.tsx
  src/@pages/order/order.tsx
  src/@pages/orderSuccess/orderSuccess.tsx
  src/@pages/review/review.tsx
  src/assets/icon/orderReceiptIc.svg
  src/core/order/colorPicker.ts
  src/core/order/styleFonts.ts
  src/index.css
  src/recoil/order/fontStyle.ts
  src/recoil/order/orderMoney.ts
  src/recoil/order/orderStep.ts
  src/recoil/order/selectCatogry.ts
  src/type/order/orderStyleData.ts
Labels: feat-function, feat-UI, 지수

#38 Feat#30 order/payment
  package.json
  src/@components/order/orderFooter/orderFooter.tsx
  src/@components/order/orderStyle/preview/style.ts
  src/@pages/checkout.tsx
  src/@pages/orderCancel/orderCancel.tsx
  src/@pages/orderFail/orderFail.tsx
  src/@pages/orderSuccess/orderSuccess.tsx
  src/Router.tsx
  src/api/payKakao.ts
  vite.config.ts
  yarn.lock
Labels: feat-function, feat-UI, 지수

#39 Feat#37 order/payment retry
  index.html
  package.json
  src/@components/order/orderBuy/style.ts
  src/@components/order/orderFooter/orderFooter.tsx
  src/@components/order/orderOption/style.ts
  src/@components/order/orderStyle/preview/preview.tsx
  src/@components/order/orderStyle/preview/style.ts
  src/@components/order/orderStyle/randomStyle/randomStyle.tsx
  src/@components/order/orderStyle/step1/style.ts
  src/@pages/orderCancel/orderCancel.tsx
  src/@pages/orderCancel/style.ts
  src/@pages/orderFail/orderFail.tsx
  src/@pages/orderFail/style.ts
  src/@pages/payment/constants.ts
  src/@pages/payment/index.tsx
  src/@pages/payment/payment.tsx
  src/@pages/payment/type.ts
  src/@pages/payment/utils.tsx
  src/App.tsx
  src/Router.tsx
  src/assets/icon/orderFailIc.svg
  src/assets/icon/randomStyle1Ic.svg
  src/assets/icon/randomStyle2Ic.svg
  src/assets/icon/randomStyle3Ic.svg
  src/assets/icon/randomStyle4Ic.svg
  src/assets/index.ts
  src/core/order/styleFonts.ts
  src/main.tsx
  src/style/globalStyle.ts
  src/style/theme.ts
  tsconfig.json
  window.d.ts
  yarn.lock
Labels: feat-function, feat-UI, 지수

#42 Feat#36 order/fix post
  src/@components/order/orderFooter/orderFooter.tsx
  src/@components/order/orderStyle/step1/style.ts
  src/@pages/orderSuccess/orderSuccess.tsx
  src/assets/icon/orderBuyActiveIc.svg
  src/assets/icon/orderBuyUnActiveIc.svg
  src/recoil/order/fontStyle.ts
  src/recoil/order/moveNextPage.ts
  src/recoil/order/orderMoney.ts
  src/recoil/order/orderStep.ts
  src/recoil/order/selectCatogry.ts
  src/recoil/order/selectOptions.ts
Labels: feat-function, feat-UI, 지수

#43 Feat#40 order/divide components
  src/@components/common/orderMoney/orderMoney.tsx
  src/@components/common/orderMoney/style.ts
  src/@components/common/orderReceipt/orderReceipt.tsx
  src/@components/common/orderReceipt/style.ts
  src/@components/order/orderBuy/orderBuy.tsx
  src/recoil/users.ts
Labels: refactor, 지수
